#include "../Common/verdefs.h"

#ifndef RC_COMPILATION
#define VERSION_TEXT(string)	L ##string
#else
#define VERSION_TEXT(string)	string
#endif

#define STRINGIZE_HELPER(x)	VERSION_TEXT(#x)
#define STRINGIZE(x)		STRINGIZE_HELPER(x)

#define U2EC_BUILD_STRING	STRINGIZE(U2EC_MAJOR_VERSION) VERSION_TEXT(".") STRINGIZE(U2EC_MINOR_VERSION) VERSION_TEXT(".") STRINGIZE(U2EC_BUILDNUM) VERSION_TEXT(".0")
#define U2EC_DATE_STRING	STRINGIZE(U2EC_BUILD_MONTH) VERSION_TEXT("-") STRINGIZE(U2EC_BUILD_DATE) VERSION_TEXT("-") STRINGIZE(U2EC_BUILD_YEAR)

#define U2EC_LegalCopyright	"Copyright © ELTIMA Software 2000-2015"
